# -*- coding: utf-8 -*-
"""SoundCloudTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mEk4395OF41qJhgVXcM00wLkfO3DuTLF
"""

# !pip install soundcloud-lib

from sclib import SoundcloudAPI, Track, Playlist

api = SoundcloudAPI()

# 任意のtrackURL
track = api.resolve('https://soundcloud.com/brandnewidolsociety/romeosheart')

filename = f'./{track.artist} - {track.title}.mp3'

# trackをmp3で保存
with open(filename, 'wb+') as fp:
  track.write_mp3_to(fp)

# trackの持つプロパティをすべて表示
track = api.resolve('https://soundcloud.com/orco-350884854/diamond-dustprodweirdove')
array = dir(track)
for index, item in enumerate(array):
    print('■' + str(index) + '：' + item)
    x = 'track.'+item
    print(eval(x))

# playlistのtracksをすべて表示
playlist_url = 'https://soundcloud.com/chillysource/sets/dj-kro-mix'

# assertを使う方法 -> noとtitleの設定ができない
# playlist = api.resolve(playlist_url)
# assert type(playlist) is Playlist
# for track in playlist.tracks:
#     print(str(track.track_no) + ':' + track.title)

# enumarateを使う方法
playlist = api.resolve(playlist_url)
for track_number, track in enumerate(playlist):
    track.track_no = track_number
    track.album = playlist.title
    print(str(track.track_no) + ':' + track.title + ' >> ' + track.album)